#!/bin/sh

# support for dpms
revert() {
    xset dpms 0 0 0
}
trap revert HUP INT TERM

# ScreenShot
scrot /tmp/screen.png
convert /tmp/screen.png -scale 10% -scale 1000% /tmp/screen.png

# Effect
[ -f $1 ] && convert /tmp/screen.png $1 -gravity center -composite -matte /tmp/screen.png

# Pause music
[ ! $(playerctl status) = "Playing" ] || playerctl pause

# Lock
xset +dpms dpms 5 5 5
#xmodmap $HOME/.xmodmap.lock
i3lock -i /tmp/screen.png #&& echo mem > /sys/power/state

# Clean
revert
#xmodmap $HOME/.xmodmap
rm /tmp/screen.png

