#!/bin/sh

source $(dirname $0)/config

(echo " $@"; sleep $DURATION)\
| lemonbar \
        -f "$FONT_MONO" -f "$FONT_AWESOME"\
        -f "$FONT_CJK" -f "$FONT_ICON"\
        -F "$COLOR_FOREGROUND"\
        -B "$COLOR_BACKGROUND"\
        -g "$NOTIFY_GEOMETRY"\
        -u $LINEHEIGHT
