#!/bin/bash
source $(dirname $0)/config

# WIFI ICONS
# 

#wiface=`iw dev wl* | grep Interface | cut -d ' ' -f2`
wiface=wlp0s20f3

QUAL=`iwconfig $wiface | grep 'Link Quality=' | awk '{gsub(/[=/]/," "); print $3}'`
MAX=`iwconfig $wiface | grep 'Link Quality=' | awk '{gsub(/[=/]/," "); print $4}'`
PERC=`echo $QUAL*100/$MAX | bc`

icon=""
case $PERC in
    [0-4])
        icon=""
    ;;
    [4-9])
        icon=""
    ;;
    [2-3]*)
        icon=""
    ;;
    [4-5]*)
        icon=""
    ;;
    [6-7]*)
        icon=""
    ;;
    *)
        icon=""
    ;;
esac

echo "%{F$COLOR_ICON}$icon%{F-}"
