#!/bin/bash
source $(dirname $0)/config

temp=$((`sensors | grep "Package id 0" | cut -d'+' -f2 | head -c2`))

if [[ $temp > 49 ]]; then
    # output="%{F$COLOR_ICON}  %{F$COLOR_URGENT}$temp°%{F-}"
    output="%{F$COLOR_ICON}  %{F$COLOR_URGENT}$temp°%{F-}"
else
    # output="%{F$COLOR_ICON}  %{F-}$temp°"
    output="%{F$COLOR_ICON}  %{F-}$temp°"
fi

echo $output;
