#!/bin/sh
# Give dmenu list of all fontawesome characters to copy.
# Shows the selected character in dunst if running.

# Must have xclip installed to even show menu.
xclip -h 2> /dev/null || exit

. ${HOME}/.cache/wal/colors.sh
chosen=$(grep -v "#" ~/.local/lib/fonts/fontawesome | dmenu -i -l 20 -nb $color0 -nf $color15 -sb $color1 -sf $color15 -fn Font\ Awesome\ 5\ Free-16)

[ "$chosen" != "" ] || exit

c=$(echo "$chosen" | sed "s/ .*//")
echo "$c" | tr -d '\n' | xclip -selection clipboard
pgrep -x dunst >/dev/null && notify-send "'$c' copied to clipboard."

s=$(echo "$chosen" | sed "s/.*; //" | awk '{print $1}')
echo "$s" | tr -d '\n' | xclip
pgrep -x dunst >/dev/null && notify-send "'$s' copied to primary."
