#! /bin/sh

xsetroot -cursor_name left_ptr

# source the colors.
. "${HOME}/.cache/wal/colors.sh"

# start hotkeys daemon
pgrep -u `whoami` sxhkd || sxhkd -m 1 &

MON=1
NDES=12
NMON=$(bspc query -M | wc -l)

for monitor in $(bspc query -M); do
    SDES=$(( $MON + ($NDES / $NMON - 1) * ($MON - 1) ))
    EDES=$(( $SDES + $NDES / $NMON - 1 ))

    # assign desktops to physical monitors
    bspc monitor $monitor -n "$MON" -d $(echo "echo 1/{$SDES..$EDES}" | sh)

    # start panels
    . ${HOME}/.config/lemonbar/lemonrc $((${MON}-1)) > ~/.panel_bar_$((${MON}-1)).log &

    let MON++
done

bspc config border_width 0
bspc config window_gap 5
bspc config top_padding 24

bspc config split_ratio 0.50

bspc config single_monocle true
bspc config borderless_monocle true
# bspc config left_monocle_padding 2
# bspc config right_monocle_padding 2
# bspc config top_monocle_padding 2
# bspc config bottom_monocle_padding 2
# bspc config gapless_monocle true

bspc config focus_follows_pointer true

# Set the border colors.
bspc config normal_border_color "$color1"
bspc config active_border_color "$color2"
bspc config focused_border_color "$color15"
bspc config presel_feedback_color "$color1"

# Set the rules
for conf in $HOME/.config/bspwm/rules.d/*.bspwmrc; do
    . $conf
done
