#! /bin/sh

wid=$1
class=$2
instance=$3
consequences=$4

case "$instance" in
    fontforge)
        title=$(xtitle "$wid")
        case "$title" in
            Layers|Tools|Warning)
                echo "focus=off"
                ;;
        esac
        ;;
esac

case "$class" in
    QuickMedia*)
        eval "$consequences"
        [ "$state" ] || echo "state=floating"
        ;;
    Lutris|Liferea)
        eval "$consequences"
        [ "$state" ] || echo "state=pseudo_tiled"
        ;;
esac
